/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module muxrightsign_9 (
    input [2:0] b,
    input [7:0] a,
    output reg [7:0] x
  );
  
  
  
  reg [7:0] tp1;
  
  reg [7:0] tp2;
  
  always @* begin
    if (b[2+0-:1] == 1'h1) begin
      tp1[4+3-:4] = {3'h4{a[7+0-:1]}};
      tp1[0+3-:4] = a[4+3-:4];
    end else begin
      tp1 = a;
    end
    if (b[1+0-:1] == 1'h1) begin
      tp2[6+1-:2] = {2'h2{tp1[7+0-:1]}};
      tp2[0+5-:6] = tp1[2+5-:6];
    end else begin
      tp2 = tp1;
    end
    if (b[0+0-:1] == 1'h1) begin
      x[7+0-:1] = tp2[7+0-:1];
      x[0+6-:7] = tp2[1+6-:7];
    end else begin
      x = tp2;
    end
  end
endmodule
