/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shift_5 (
    input [1:0] alufn10,
    input [7:0] a,
    input [2:0] b,
    output reg [7:0] out
  );
  
  
  
  wire [8-1:0] M_mleft_x;
  reg [3-1:0] M_mleft_b;
  reg [8-1:0] M_mleft_a;
  muxleft_7 mleft (
    .b(M_mleft_b),
    .a(M_mleft_a),
    .x(M_mleft_x)
  );
  
  wire [8-1:0] M_mright_x;
  reg [3-1:0] M_mright_b;
  reg [8-1:0] M_mright_a;
  muxright_8 mright (
    .b(M_mright_b),
    .a(M_mright_a),
    .x(M_mright_x)
  );
  
  wire [8-1:0] M_mrights_x;
  reg [3-1:0] M_mrights_b;
  reg [8-1:0] M_mrights_a;
  muxrightsign_9 mrights (
    .b(M_mrights_b),
    .a(M_mrights_a),
    .x(M_mrights_x)
  );
  
  always @* begin
    M_mleft_a = a;
    M_mleft_b = b;
    M_mright_a = a;
    M_mright_b = b;
    M_mrights_a = a;
    M_mrights_b = b;
    
    case (alufn10)
      2'h0: begin
        out = M_mleft_x;
      end
      2'h1: begin
        out = M_mright_x;
      end
      2'h3: begin
        out = M_mrights_x;
      end
      default: begin
        out = 8'hff;
      end
    endcase
  end
endmodule
